data_dir: C:\Users\OWNER\kaggle\CSIRO\kakao\data
input_dir: C:\Users\OWNER\kaggle\CSIRO\kakao\data
processed_dir: C:\Users\OWNER\kaggle\CSIRO\kakao\processed_data
outputs_dir: C:\Users\OWNER\kaggle\CSIRO\kakao\outputs
model_dir: C:\Users\OWNER\kaggle\CSIRO\kakao\models
# dicom_series_stored_dir: /content/drive
# output_npz_dir: /cotent/drive/MyDrive/kaggle/CSIRO/processed_data
# src_root_dir: /content/drive/MyDrive/kaggle/CSIRO/data/unzipped_series